version: 2
jobs:

  # Build and verify the generated HTML
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: public
    steps:
      # Install git
      - run: apk update && apk add git

      # Checkout the repository
      - checkout
      
      # Install git submodules for managing third-party dependencies
      #- run: git submodule sync && git submodule update --init
      
      # Build with Hugo
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR

      # Test the generated HTML
      - run:
          name: Test our generated HTML files
          command: |
            htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html \
            --empty-alt-ignore --disable-external

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/hugo
          # Must be relative path from root
          paths:
             - public/
  
  # Publish the generated HTML to the RDC Website
  publish:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/hugo

      # Install ncftp
      - run: apk update && apk add ncftp

      # Publish into separate folder
      - run: |
           ncftpput -R -v \
             -u $FTP_USERNAME \
             -p $FTP_PASSWORD \
             $FTP_HOST $FTP_FOLDER-$CIRCLE_WORKFLOW_ID \
             public/

# Glue the pipelines together
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish:
          requires:
            - build