version: 2
jobs:

  # Build and verify the generated HTML
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: public
    steps:
      # Install git
      - run: 
          name: Install pipeline utilitie(s)
          command: apk update && apk add git

      # Checkout the repository
      - checkout
      
      # Install git submodules for managing third-party dependencies
      #- run: git submodule sync && git submodule update --init
      
      # Build with Hugo
      - run: 
          name: Build the Hugo static content
          command: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/hugo
          # Must be relative path from root
          paths:
             - public/

  # Validate the generated HTML
  validate:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: public
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/hugo

      # Test the generated HTML
      - run:
          name: Test our generated HTML files
          command: |
            htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html \
            --empty-alt-ignore --disable-external


  # Publish the generated HTML to the RDC Website
  publish:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/hugo

      # Install ncftp
      - run: 
          name: Install pipeline utilitie(s)
          command: apk update && apk add ncftp

      # Publish into separate folder
      - deploy: 
          name: Upload content to RDC FTP server
          command: |
            echo "mkdir $FTP_FOLDER-$CIRCLE_WORKFLOW_ID" > create_dir.cmd && \
            ncftp -u $FTP_USERNAME -p $FTP_PASSWORD $FTP_HOST < create_dir.cmd && \
            (cd public && ncftpput -R -v \
              -u $FTP_USERNAME \
              -p $FTP_PASSWORD \
              $FTP_HOST $FTP_FOLDER-$CIRCLE_WORKFLOW_ID \
              .)

      - deploy: 
          name: Bring content live
          command: |
            echo "rename $FTP_FOLDER $FTP_FOLDER-$(date +"%Y-%m-%d_%H-%M-%S")" > rename_dirs.cmd && \
            echo "rename $FTP_FOLDER-$CIRCLE_WORKFLOW_ID $FTP_FOLDER" >> rename_dirs.cmd && \
            ncftp -u $FTP_USERNAME -p $FTP_PASSWORD $FTP_HOST < rename_dirs.cmd

# Glue the jobs together
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - validate:
          requires:
            - build
      - publish:
          requires:
            - validate
          filters:
            branches:
              only: master